### ISSUE TITLE
Bug in server function

### ISSUE THREAD

**Issue by Daenara** [wuub/rxv#85]
Firstly, I have to say thank you very much for your work. I found this today in basically my last attempt to get my receiver to play a specific playlist. Maybe I should have added python to my search a year ago and spared me quite a few hours of frustrations.

So as soon as I found this I started looking at the code and found the server function which is pretty much exactly what I need and behind me music is playing that I started with exactly this function. It does have a slight but though. If I point it at "server>music>playlists>playlist" this is what happens:

```
Traceback (most recent call last):
  File "L:/Seafile/Programmieren/Python/receiverTest/test.py", line 19, in <module>
    receiver.server("Twonky>Musik>Wiedergabelisten>Blutengel")
  File "L:\Seafile\Programmieren\Python\venv\receiverTest\lib\site-packages\rxv\rxv.py", line 902, in server
    if value == layers[menu.layer - 1]:
IndexError: list index out of range
```

Walking over to my receiver and taking a look at the display shows me a list of all the songs in the playlist which is obviously the furthest layer in I can be so the out of range error makes sense but I think it should detect if it is the furthest layer in and, if no song was specified just start playing the first available song. I am pretty sure this is a consequence of copying the code from the net radio functionality because net radio does not have songs in playlists. 

As soon as I specify "server>music>playlists>playlist>song" it works as expected and I can't wait to finally automate putting on my going to sleep playlist after telling my voice assistant "good night". That was literally the last bit of functionality missing for this project. 

EDIT: Wrote a fix: #86

**Comment by Daenara** [comment]
I wrote a fix and made a pull request. Not sure if I can link it myself, I am a noob at using github so here is the link:

[Pull request](https://github.com/wuub/rxv/pull/86)
